version: '3.4'

services:
  dotnetapitoredis:
    image: ${DOCKER_REGISTRY}dotnetapitoredis
    build:
      context: .
      dockerfile: dotnetApiToRedis/Dockerfile
  itchat:
      image: ${DOCKER_REGISTRY}itchatmsg
      build: 
        context: ./itchat
        dockerfile: Dockerfile
      depends_on:
        - dotnetapitoredis